spring:
  application:
    name: kernfolio

  datasource:
    url: jdbc:postgresql://localhost:5432/kernfolio
    username: ${DB_USER:kernfolio}
    password: ${DB_PASSWORD:kernfolio}

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  thymeleaf:
    cache: false

optimizer:
  base-url: ${OPTIMIZER_BASE_URL:http://localhost:8000}

server:
  port: 8080
